- name: Run roles on all Linux inventory nodes
  hosts: linux
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_managed: "Managed by Ansible"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  roles:
    - datadisk-n01619534
    - profile-n01619534
    - user-n01619534
    - webserver-n01619534
