---
- name: Install packages on CentOS or RedHat
  package:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  loop: "{{ packages_to_install }}"
