# roles/profile_mgmt/tasks/main.yml
---
- name: Create file on the automation machine
  ansible.builtin.file:
    path: "{{ locfile_path }}"
    state: touch

- name: Copy locfile to managed nodes
  ansible.builtin.file:
    path: "/tmp/locfile"
    owner: "{{ locfile_owner }}"
    group: "{{ locfile_group }}"
    mode: "{{ locfile_permissions }}"
    state: touch
    
- name: Set SELinux file type to etc_t
  sefcontext:
    target: "/tmp/locfile"
    setype: etc_t
    state: present

- name: Display status of /tmp/locfile
  ansible.builtin.stat:
    path: "/tmp/locfile"
  register: locfile_status

- debug:
    var: locfile_status

- name: Create empty file in user's home directory
  ansible.builtin.file:
    path: "{{ emptyfile_path }}"
    state: touch
