- name: Add cloudadmins group
  ansible.builtin.group:
    name: cloudadmins
    state: present

- name: Add user accounts
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: "~/.ssh/id_rsa"  # Update SSH key file path
    ssh_key_type: rsa
    ssh_key_comment: "{{ item.name }}@{{ ansible_hostname }}"
    password: ""
  loop: "{{ users }}"

- name: Distribute SSH keys for users
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  # Update SSH key file path
  loop: "{{ users }}"
  notify: reload ssh

- name: Add users to wheel group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Add users to wheel group
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "wheel"
    append: yes
  loop: "{{ users }}"
